[package]
name = "librespeed-rs"
version = "1.0.1"
edition = "2021"

[dependencies]
#async net
tokio = {version = "1.38.0", features = ["net","io-util","rt","macros","rt-multi-thread"]}
#image processing
imageproc = "0.25.0"
ab_glyph = "0.2.26"
#serializer
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
#databases
uuid = { version = "1.8.0", features = ["v4"] }
chrono = "0.4.38"
mysql = { version = "25.0.1",default-features = false }
postgres = "0.19.7"
rusqlite = { version = "0.31.0",features = ["bundled"] }
#conf
clap = { version = "4.5.7",features = ["std"],default-features = false }
toml = "0.8.14"
#web
sha2 = "0.10.8"
tera = { version = "1.20.0",default-features = false }
#logging
env_logger = { version = "0.11.3",default-features = false,features = ["auto-color","humantime"] }
log = "0.4.21"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
lto = true
strip = true
