[package]
name = "librespeed-rs"
version = "1.3.0"
edition = "2021"
authors = ["Sudo Dios"]
description = "Rust backend for LibreSpeed"

[dependencies]
#async net
tokio = {version = "1.40.0", features = ["net","io-util","rt","macros","rt-multi-thread"]}
tokio-rustls = {version = "0.26.0", features = ["logging","tls12","ring"], default-features = false}
webpki-roots = "0.26.5"
rustls-pemfile = "2.1.3"
socket2 = "0.5.7"
#ip
maxminddb = "0.24.0"
#image processing
imageproc = "0.25.0"
ab_glyph = "0.2.28"
#serializer
serde_json = "1.0.127"
serde = { version = "1.0.209", features = ["derive"] }
#databases
uuid = { version = "1.10.0", features = ["v4"] }
chrono = "0.4.38"
mysql = { version = "25.0.1",default-features = false }
postgres = "0.19.8"
rusqlite = { version = "0.32.1",features = ["bundled"] }
#conf
clap = { version = "4.5.16",features = ["std","color","help","usage"],default-features = false }
toml = "0.8.19"
#web
sha2 = "0.10.8"
tera = { version = "1.20.0",default-features = false }
#logging
env_logger = { version = "0.11.5",default-features = false,features = ["auto-color","humantime"] }
log = "0.4.22"
indicatif = "0.17.8"
#assets
include_dir = "0.7.4"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
lto = true
strip = true
