[package]
name = "librespeed-rs"
version = "1.0.1"
edition = "2021"

[dependencies]
#async net
tokio = {version = "1.39.2", features = ["net","io-util","rt","macros","rt-multi-thread"]}
tokio-rustls = "0.26.0"
webpki-roots = "0.26.3"
rustls-pemfile = "2.1.2"
#image processing
imageproc = "0.25.0"
ab_glyph = "0.2.28"
#serializer
serde_json = "1.0.121"
serde = { version = "1.0.204", features = ["derive"] }
#databases
uuid = { version = "1.10.0", features = ["v4"] }
chrono = "0.4.38"
mysql = { version = "25.0.1",default-features = false }
postgres = "0.19.8"
rusqlite = { version = "0.32.1",features = ["bundled"] }
#conf
clap = { version = "4.5.11",features = ["std"],default-features = false }
toml = "0.8.17"
#web
sha2 = "0.10.8"
tera = { version = "1.20.0",default-features = false }
#logging
env_logger = { version = "0.11.5",default-features = false,features = ["auto-color","humantime"] }
log = "0.4.22"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
lto = true
strip = true
